<?php
// $Id$
/**
 * @file
 * Drupal Services plugin for Clients module
 * @author Django Beatty - adub
 */

/**
 * Contains classes extending clients_connection_base.
 */
require_once('clients_drupal.inc');

/**
 * Implementation of hook_help()
 * @param path which path of the site we're displaying help
 * @param arg array that holds the current path as would be returned from arg() function
 * @return help text for the path
 */
function clients_drupal_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#clients_drupal":
      $output = '<p>'.  t("Clients - Drupal Services.") .'</p>';
      break;
  }
  return $output;
}

/**
 * Implementation of hook_clients_connection_type_info().
 *
 * Define the connection type we provide.
 */
function clients_drupal_clients_connection_type_info() {
  return array(
    // Key by machine name. Used as the base for hooks.
    'drupal_services' => array(
      'module' => 'clients_drupal', // This module. (Saves invoker mucking about putting that in.)
      'class'  => 'ClientsServicesDrupal',
      'label'  => t('Drupal Services'), // Human-readable label.
    ),
    'drupal_services_5' => array(
      'module' => 'clients_drupal',
      'class'  => 'ClientsServicesDrupal_5',
      'label'  => t('Drupal Services 5'),
    ),
    'drupal_services_6_2' => array(
      'module' => 'clients_drupal',
      'class'  => 'ClientsServicesDrupal_6_2',
      'label'  => t('Drupal Services 6.x-2.x'),
    ),
  );
}

/**
 * Implementation of hook_perm()
 * @TODO
 * @return array An array of valid permissions for the clients_drupal module
 */
function clients_drupal_perm() {
  return array('clients_drupal admin');
}

/**
 * Implementation of hook_menu()
 */
function clients_drupal_menu() {
  $items = array();
  $items['admin/settings/clients/settings/drupal'] = array(
     'title' => 'Configure Drupal',
     'page callback' => 'drupal_get_form',
     'page arguments' => array('clients_drupal_admin'),
     'access arguments' => array('clients_drupal admin'),
     'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Form builder for the connection.
 *
 * This should be of the form client_connection_TYPE_form.
 */
function client_connection_drupal_services_form(&$form_state, $type, $cid = NULL) {
  
  $form = array();

  if (is_null($cid)) {
    $new = TRUE;
    drupal_set_title('Add Drupal services connection');
  }
  else {
    $connection = clients_connection_load((int) $cid);
    $form['cid'] = array(
      '#type' => 'value',
      '#value' => $cid,
    );
  }
  
  $form['type'] = array(
    '#type' => 'value',
    '#value' => $type,
  );
  
  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Connection name'),
    '#default_value' => $cid ? $connection->name : '',
    '#size' => 50,
    '#maxlength' => 100,
    '#description' => t('Must be unique, any characters allowed'),
    '#required' => TRUE,
  );
  
  $form['endpoint'] = array(
    '#type' => 'textfield',
    '#title' => t('Connection endpoint'),
    '#default_value' => $cid ? $connection->endpoint : '',
    '#size' => 50,
    '#maxlength' => 100,
    '#description' => t('Remote service URL e.g. http://mysite.com/services/xmlrpc'),
    '#required' => TRUE,
  );
  
  $form['configuration'] = array(
    '#type' => 'fieldset',
    '#title' => t('Configuration'),
    '#collapsible' => FALSE,
    '#tree' => TRUE,
  );
  
  $form['configuration']['domain'] = array(
    '#type' => 'textfield',
    '#title' => t('Domain'),
    '#default_value' =>  $cid ? $connection->configuration['domain'] : '',
    '#size' => 50,
    '#maxlength' => 100,
    '#description' => t('This should be same as the \'Domain\' field used by the Services authentication key on the server you are connecting to.'),
    '#required' => TRUE,
  );
  $form['configuration']['servicekey'] = array(
    '#type' => 'textfield',
    '#title' => t('Service key'),
    '#default_value' =>  $cid ? $connection->configuration['servicekey'] : '',
    '#size' => 50,
    '#maxlength' => 40,
    '#attributes' => array('autocomplete' => 'off'),
    '#description' => t('This should be same as the \'Key\' field used by the Services authentication key on the server you are connecting to.'),
    '#required' => TRUE,
  );
  $form['configuration']['username'] = array(
    '#type' => 'textfield',
    '#title' => t('Service username'),
    '#default_value' =>  $cid ? $connection->configuration['username'] : '',
    '#size' => 30,
    '#maxlength' => 60,
    '#attributes' => array('autocomplete' => 'off'),
    '#description' => t('This should be same as the username on the server you are connecting to.'),
    '#required' => TRUE,
  );

  
  $password_desc = $cid ? 
    t('This should be same as the password on the server you are connecting to. Leave blank unless you need to change this.') : 'This should be same as the password on the server you are connecting to.';
    
  $form['configuration']['password'] = array(
    '#type' => 'password',
    '#title' => t('Service password'),
    '#size' => 30,
    '#maxlength' => 60,
    '#attributes' => array('autocomplete' => 'off'),
    '#description' => $password_desc,
    '#required' => $new,
  );

  $form['configuration']['methods_enabled'] = array(
    '#type' => 'textarea',
    '#title' => t('Services'),
    '#default_value' =>  $cid ? $connection->configuration['methods_enabled'] : '',
    '#description' => t('List of Drupal services on remote servers that you want to enable here (e.g. views.service). Resources can select from this list. One per line.'),
  );

  $form['configuration']['views_enabled'] = array(
    '#type' => 'textarea',
    '#title' => t('Views'),
    '#default_value' =>  $cid ? $connection->configuration['views_enabled'] : '',
    '#description' => t('List of Drupal views on remote servers. Resources can select from this list. One per line.'),
  );

  $button_text = $new ? t('Add connection') : t('Save connection');
  $form['buttons']['submit'] = array(
    '#type' => 'submit',
    '#value' => $button_text,
  );
  
  return $form;
}

/**
 * Submit handler for the Drupal services connection edit form.
 */
function client_connection_drupal_services_form_submit($form, &$form_state) {
  // Presence of the cid tells us whether we're editing or adding a new connection.
  $new = !isset($form_state['values']['cid']);

  if ($new) {
    $form_state['values']['configuration']['password'] = clients_drupal_encrypt($form_state['values']['configuration']['password']);
  }
  else {
    // Prepare password for serialized storage
    if (empty($form_state['values']['configuration']['password'])) {
      // Need to load connection and set password to original if blank
      $original = clients_connection_load((int) $form_state['values']['cid']);
      $form_state['values']['configuration']['password'] = $original->configuration['password'];
    }
    $form_state['values']['configuration']['password'] = clients_drupal_encrypt($form_state['values']['configuration']['password']);
  }

  if ($new) {
    drupal_write_record('clients_connections', $form_state['values']);
  }
  else {
    drupal_write_record('clients_connections', $form_state['values'], 'cid');
  }

  drupal_set_message(t('Connection saved.'));
  $form_state['redirect'] = 'admin/settings/clients/connections';
}

/**
 * Implementation of hook_validate()
 * 
 * TODO: this doesn't seem to get used.
 */
function clients_drupal_add_validate($form, &$form_state) {

    if(clients_connection_load($form['name']['#value'])) {
        form_set_error('name', 'A service by this name already exists!');
    }

    $connection = new stdClass;
    $connection->name = $form['name']['#value'];
    $connection->endpoint = $form['endpoint']['#value'];
    $connection->domain = $form['configuration']['domain']['#value'];
    $connection->servicekey = $form['configuration']['servicekey']['#value'];
    $connection->username = $form['configuration']['username']['#value'];
    $connection->password = $form['configuration']['password']['#value'];

    $testconnect = ClientsServicesDrupal::connect($connection);
    if(!is_array($testconnect) || !isset($testconnect['sessid'])) {
        form_set_error('endpoint', "Couldn't connect");
    } else {
        $testuser = ClientsServicesDrupal::getUser($connection);
        if(!is_array($testuser) || !isset($testuser['sessid'])) {
            form_set_error('username', isset($testuser->message) ? $testuser->message : "Couldn't log in");
        }
    }
}

/**
 * Implementation of hook_clients_connection_load
 */
function clients_drupal_clients_connection_load(&$connection) {
  if ($connection->type == 'drupal_services') {
    $connection->configuration['password'] = clients_drupal_decrypt($connection->configuration['password']); // or ***
  }
}


/**
 * Implementation of hook_clients_service_options
 */
function clients_drupal_clients_service_options($connection, $wrapper, $wrapper_values, $resource) {
  if ($connection->type != 'drupal_services') {
    return;
  }

  $form = array();
  $connection = clients_connection_load((int) $connection->cid);
  $methods = array_map('trim', explode("\n", trim($connection->configuration['methods_enabled'])));
  $methods = array_combine($methods, $methods);

  $options_selected =
    (isset($wrapper_values['options']) ? $wrapper_values['options'] :
    (isset($resource->rid) ? $resource->configuration['options'] :
    array()));

  // if we change connection and method doesn't exist, reset
  if(!in_array($options_selected['method'], $methods)) {
    $options_selected['method'] = key($methods);
  }

  $form['method'] = array(
    '#type' => 'select',
    '#title' => t('Method'),
    '#default_value' => $options_selected['method'],
    '#options' => $methods,
    '#description' => t('Choose method'),
    '#required' => TRUE,
    '#ahah' => array(
      'path' => ahah_helper_path(array($wrapper)),
      'wrapper' => $wrapper,
      'method' => 'replace',
      'effect' => 'fade',
    ),
  );

  if($options_selected['method'] == 'views.get') {

    $views = array_map('trim', explode("\n", trim($connection->configuration['views_enabled'])));
    $views = array_combine($views, $views);

    $form['view'] = array(
      '#type' => 'select',
      '#title' => t('View'),
      '#default_value' => $options_selected['view'],
      '#options' => $views,
      '#description' => t('Choose view'),
    );
    $form['arguments']['first'] = array(
      '#type' => 'textfield',
      '#title' => t('Argument'),
      '#default_value' => $options_selected['arguments']['first'],
      '#size' => 10,
      '#maxlength' => 30,
    );
    $form['offset'] = array(
      '#type' => 'textfield',
      '#title' => t('Offset'),
      '#default_value' => $options_selected['offset'],
      '#size' => 3,
      '#maxlength' => 4,
    );
    $form['limit'] = array(
      '#type' => 'textfield',
      '#title' => t('Limit'),
      '#default_value' => $options_selected['limit'],
      '#size' => 3,
      '#maxlength' => 4,
    );
  }
  else {
      /**
       * @todo some 'method not supported' handling
       */
  }
  return $form;
}

/**
 * Implementation of hook_clients_setparams
 */
function clients_drupal_clients_setparams(&$resource, $arg) {
  $connection = clients_connection_load((int)$resource->cid); // need to make static?
  if($connection->type == 'drupal_services') {
    foreach($arg as $key => $value) {
      // doesn't support multiple args...
      if($key == 'argument') {
        $resource->configuration['options']['arguments']['first'] = str_replace(' ', '+', $value);
      }
      else {
        $resource->configuration['options'][$key] = str_replace(' ', '+', $value);
      }
    }
  }
}

/**
 * Implementation of hook_clients_arguments
 */
function clients_drupal_clients_arguments($connection)  {
//  $connection = clients_connection_load((int)$source['connection']);
  if($connection->type == 'drupal_services') {
    $arg = new stdClass;
    $arg->name = 'argument';
    $arg->title = t('Argument');
    $arg->help = t('Argument to pass to resource');
    return array($arg);
  }
}


/**
 * Implementation of hook_clients_call
 *
 * TODO: rename to hook_clients_call_resource
 */
function clients_drupal_clients_call($connection, $serviceOptions) {
  if ($connection->type == 'drupal_services'){
    $serviceConfig = clients_connection_load((int) $connection->cid);
    return ClientsServicesDrupal::call($serviceConfig, $serviceOptions);
  }
}

/**
 * Caller function. This gets us into the class.
 */
function drupal_services_clients_call($connection, $method, $parameters = array()) {
  return ClientsServicesDrupal::call_method($connection, $method, $parameters);
}
 
/**
 * Implementation of hook_clients_fields - refactor as inc file?
 * Allows us to get field for a specific resource. Default fields are set at the connection type level here and additional custom field will be defined per resource (@todo). This will allow adding of remote cck fields (for example) for a specific resource (e.g. a certain view). This function will need to aggregate these with the base ones. (Otherwise this function is used to return all available fields.)
 */
function clients_drupal_clients_fields($resource = NULL) {
  if ($resource) {
    $connection = clients_connection_load((int)$resource->cid);
    if ($connection->type != 'drupal_services') {
      return;
    }

    $result = clients_call($resource);
    
    if (isset($result[0]->data[0])) {

      $fields = array_keys($result[0]->data[0]);
      $fieldset = array();
      foreach($fields as $field) {
        $fieldset[$field] = array('name' => $field, 'description' => '');
      }
      return $fieldset;
    } 
    else {
      drupal_set_message('No fields were returned');
      return;
    }
  }

// need to define behaviour if no resource specified - should this display:
// - no fields
// - a preset list of fields (from each service module)
// - all possible fields from currently defined resources
  return array();

}

/**
 * @return array Form
 */
function clients_drupal_admin() {
  $form = array();
  $options = clients_drupal_encryption_methods();
  $form['clients_drupal_encryption_method'] = array(
    '#type' => 'select',
    '#title' => t('Remote password encryption method'),
    '#default_value' => variable_get('clients_drupal_encryption_method', 'no_encryption'),
    '#options' => $options,
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

function clients_drupal_encryption_methods() {
  $options = module_invoke_all('clients_drupal_encryption_methods');
  $options['no_encryption'] = t('No encryption');
  return $options;
}

function clients_drupal_encrypt($val) {
  $encryption_method = variable_get('clients_drupal_encryption_method', 'no_encryption');
  if ($encryption_method == 'no_encryption') {
    return $val;
  }
  else {
    return module_invoke($encryption_method, 'clients_drupal_encrypt', $val);
  }
}

function clients_drupal_decrypt($val) {
  $encryption_method = variable_get('clients_drupal_encryption_method', 'no_encryption');
  if ($encryption_method == 'no_encryption') {
    return $val;
  }
  else {
    return module_invoke($encryption_method, 'clients_drupal_decrypt', $val);
  }
}
