<?php
// $Id$
/**
 * @file
 * Clients - client for feeds module 
 * @author Django Beatty - adub
 */
 
/**
 *
 */

/**
 * Implementation of hook_help()
 * @param path which path of the site we're displaying help
 * @param arg array that holds the current path as would be returned from arg() function
 * @return help text for the path
 */
function clients_feeds_help($path, $arg) {
  $output = '';  
  switch ($path) {
    case "admin/help#clients":
      $output = '<p>'.  t("Clients Feeds .") .'</p>';
      break;
  }
  return $output;
} 

/**
* Valid permissions for this module
* @return array An array of valid permissions for the clients_feeds module
*/
function clients_feeds_perm() {
  return array('access clients feeds');
} 

/**
* Implementation of hook_feeds_plugins().
*/
function clients_feeds_feeds_plugins() {
  $info = array();
  $info['FeedsClientsFetcher'] = array(
    'name' => 'Clients fetcher',
    'description' => 'Fetch data using clients resources',
    'handler' => array(
      'parent' => 'FeedsFetcher', // A plugin needs to derive either directly or indirectly from FeedsFetcher, FeedsParser or FeedsProcessor.
      'class' => 'FeedsClientsFetcher',
      'file' => 'FeedsClientsFetcher.inc',
      'path' => drupal_get_path('module', 'clients_feeds'),
    )
  );

  $info['FeedsClientsParser'] = array(
    'name' => 'Clients parser',
    'description' => 'Parses data using clients resources',
    'handler' => array(
      'parent' => 'FeedsParser', // A plugin needs to derive either directly or indirectly from FeedsFetcher, FeedsParser or FeedsProcessor.
      'class' => 'FeedsClientsParser',
      'file' => 'FeedsClientsParser.inc',
      'path' => drupal_get_path('module', 'clients_feeds'),
    )
  );

  return $info;
}


